version: '3.9'
services:
    postgres:
        image: postgres:15.1
        restart: always
        environment:
            - POSTGRES_USER=my_user
            - POSTGRES_PASSWORD=my_user
            - POSTGRES_DB=my_user
        user: root
        ports:
            - "5432:5432"
        volumes:
            - /home/my_user/volumes/postgres/data:/var/lib/postgresql/data
            - /home/my_user/volumes/postgres/config:/etc/postgresql
    postgres_setup:
        image: postgres:15.1
        user: root
        volumes:
            - /home/my_user/volumes/postgres/data:/var/lib/postgresql/data
            - /home/my_user/volumes/postgres/config:/etc/postgresql
        entrypoint: [ "bash", "-c", "chmod 750 -R /var/lib/postgresql/data && chmod 750 -R /etc/postgresql"] 
        depends_on:
            - postgres
    # pgadmin4:
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=my_user@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=my_user
    #         - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    #     user: root
    #     ports:
    #         - "5050:80"
    #     volumes:
    #         - /home/my_user/volumes/pgadmin/data:/var/lib/pgadmin
    #     depends_on:
    #         - postgres_setup
# services:
#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: ../dev-config/Dockerfile.frontend
#     ports:
#       - "5134:5134"
#     volumes:
#       - ../frontend:/usr/app
#     networks:
#       - todonet
#   db:
#     image: postgres
#     restart: always
#     shm_size: 128mb
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#       POSTGRES_USER: ${DATABASE_USERNAME}
#       POSTGRES_DB: ${DATABASE_NAME}
#       # DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#       # DATABASE_USERNAME: ${DATABASE_USERNAME}
#       # DATABASE_NAME: ${DATABASE_NAME}
#     #   POSTGRES_DB: "db" 
#     #   # PGDATA: /tmp
#     volumes:
#       # - ./data/:/var/lib/postgresql/data"
#       - db:/var/lib/postgresql/data
#     user: 1000:1000
#     networks:
#       - todonet
#
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
#     networks:
#       - todonet
#         
# networks:
#   todonet:
# volumes:
#   db:
